# Generated by Django 4.1.9 on 2023-06-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
