# Generated by Django 4.1.9 on 2023-06-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='imageLink',
            field=models.CharField(default='https://static.thenounproject.com/png/583402-200.png', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='imageLink',
            field=models.CharField(default='https://static.thenounproject.com/png/583402-200.png', max_length=500),
        ),
    ]
